### ISSUE TITLE
What is the last update version of: script.artwork.beef-matrix

### ISSUE THREAD

**Issue by burekas7** [henryjfry/script.artwork.beef-matrix#1]
Hi,

Here the zip file was uploaded a 4 months ago.
But here it seems that you updated the files a month ago.

Can you please create an updated zip? (If there was any change)

Thanks.

**Comment by henryjfry** [comment]
There was a very small change, but this wasnt a fully setup repo.  Ive added it to my main repo:
https://henryjfry.github.io/repository.thenewdiamond/repo/index.html

https://henryjfry.github.io/repository.thenewdiamond/zips/script.artwork.beef/script.artwork.beef-0.28.6.zip

**Comment by burekas7** [comment]
Thanks @henryjfry 

By the way I made a new Matrix version to the old classic Artwork Downloader if you want:
https://f2h.io/uxsk76x6crny

**Comment by burekas7** [comment]
@henryjfry 

By the way, may I ask you to add my Artwork Downloader matrix version to your "thenewdiamond" repo?
https://f2h.io/uxsk76x6crny

Thanks.

**Comment by henryjfry** [comment]
Do you have a github? Just Id like to look at it to see what its all about

What does it do additionally/different to artwork beef?
I know what artwork beef does, not sure about this one.

Is it a skin util addon you have updated for matrix?

**Comment by henryjfry** [comment]
I see its an optional dependency for "script.skin.helper.service" in the repo so ive just added it:

https://henryjfry.github.io/repository.thenewdiamond/zips/script.artwork.downloader/script.artwork.downloader-15.5.0.0.zip

**Comment by burekas7** [comment]
@henryjfry 
Thanks.
If I have updates in the future I will tell you.
I make all the work on my pc so I didn't upload it to git.

And yes, basically they are prettry the same, Downloader was the main addon before Beef came.
I found it more simple and easy to set and use.
Because Downloader stopped development somewhere between kodi 17-18,
I took it and added some feature and code fixeds.
In Titan skin you can add a button in your dialog video info so it very nice, you can see images here:
https://forum.kodi.tv/showthread.php?tid=330749&pid=3062011#pid3062011

**Comment by burekas7** [comment]
@henryjfry 

Please update and replace this zip file with the one that currently exist in your repo:
https://f2h.io/tmb1ufiuwci7

This is the same version, I just modified the settings.xml to follow the Kodi 19 standard (Otherwise the settings isn't showing well)

Thanks.

**Comment by henryjfry** [comment]
Ok but for future reference pleas DO NOT SEND ME ZIP's just send me whatever files have changed (and on a less shitty file host, i suggest "https://www.pastefile.com/" or for individual files even better pastebin).
I have to unzip, copy to the repo on my pc, copy that to the repo on my pi, run the repo update script on the pi, copy that back to my pc repo and then update.

Just the updated file I can just update the repo on my Pi directly.

Also I'm presuming that any future updates will be small and infrequent.  Im not hosting a repo on your behalf if you are going to be updating it constantly, you can learn how to do it yourself if thats the case.

**Comment by henryjfry** [comment]
https://henryjfry.github.io/repository.thenewdiamond/zips/script.artwork.downloader/script.artwork.downloader-15.5.0.1.zip

**Comment by burekas7** [comment]
Of course, I'm apology.
I will do that for the next time.

Basically it was not necessary to increase a version because I do not think anyone has installed yet.
(By the way, for some reason kodi doesn't recognize this new version number as a new update.)

And it doesn't seem that I'm going to update it constantly.
The only reasaon for the update now is the moving to Matrix and python 3.

Thanks again.

**Comment by henryjfry** [comment]
The repo script will update the main repo addon.xml and md5 hashes automatically so its easier to update the version and any file changes in the addon folder and then rerun the repo script to get everything published correctly.
I dont tend to install stuff from repos myself, so i never know if manually updating zips works at the repo side or not.

So ive setup a script to auto increment the version and run the repo update, therefore it will be easier going forward if I can just copy and paste from pastebin without having to generate a download link, download it, extract it, overwrite and then begin the repo update.

Although it sounds like this will be the last update baring any particular errors so thats fine.

**Comment by burekas7** [comment]
@henryjfry 

Hi,
What is this update of "script.extendedinfo v.3.2"?
And why did it require to change the Artwork Downloader version to 15.6?

**Comment by henryjfry** [comment]
Artwork downloaded was just incremented to get the auto repo script to build the zip and do all the md5 hashes and stuf to properly publish a repo.

script.extendedinfo v3.2, ive no idea what update that was, im on 3.29 now I think.  Again i publish incremental updates if and when literally anything changes. I setup a script to do it for me so if I remove a single line, that'll be a version change.

**Comment by henryjfry** [comment]
If you want complete visibility over artwork downloader, i suggest you publish your own repo.

**Comment by burekas7** [comment]
> Artwork downloaded was just incremented to get the auto repo script to build the zip and do all the md5 hashes and stuf to properly publish a repo.

@henryjfry 

But you have already increased the version last time from 15.5.0.0 to 15.5.0.1,
I don't understand the logic of increase it again to 15.6 if there wasn't any change.

Basically, if so, I prefer that you will remove the Artwork Downloader from your repo.
I don't want that a mess with the versions will be start.

The most updated version should be 15.5.0.0 and not another value.

Thanks.

**Comment by henryjfry** [comment]
I only changed the version number because my auto increment script can do 15.50 + 0.01 but cant do that with 15.5.0.0, hence chaning it to just a float number rather than some arbitrary version number.

So you asked me to add it to my repo, you then asked for an update. Having to do it manually was a pain so i modified my diamondinfo auto incrementing script to do it. 
Now if it does ever need an update or fix its relatively painless for me to do it.

I dont see what the problem is. Im not planning on just randomly versioning it, that last one was basically so the next time it ever does get updated it'll be easier for me to do it.
But I dont actually use it so unless you or someone else reports an issue it will sit at version 15.6

So i'd prefer to just leave it sitting there, if you want to fork it and setup whatever version number you feel like go right ahead. It would only affect people using my repo.
Anyone on the repo you setup will get whatever version you fork to.

**Comment by burekas7** [comment]
@henryjfry 

As I said, I ask that you will remove it from your repo.
(If I will open my repo in the future I want my version number to be the main value)

Thanks for you help.

**Comment by burekas7** [comment]
@henryjfry 

By the way, I found a little bug in my code.
But as I said, if it's ok from you, I ask you to remove my Artwork Downloader zips from your repo.
Thanks.
