### ISSUE TITLE
Cannot install from zip within Kodi

### ISSUE THREAD

**Issue by bartolomesoriano** [henryjfry/script.artwork.beef-matrix#3]
@henryjfry , it seems that with one of your latest commits, you removed the addon.xml file from the root folder of the addon.  Without that, you cannot do an "install from zip" of the addon inside Kodi.  Please restore this.  Thanks.

**Comment by henryjfry** [comment]
Install it from my repo:

https://henryjfry.github.io/repository.thenewdiamond/index.html

https://github.com/henryjfry/repository.thenewdiamond/blob/main/zips/script.artwork.beef/script.artwork.beef-0.28.6.zip

**Comment by bartolomesoriano** [comment]
@henryjfry , thanks, I will do that.
